/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.38.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { NinetieswhitelistAbi } from './NinetieswhitelistAbi';

export { NinetieswhitelistAbi__factory } from './factories/NinetieswhitelistAbi__factory';
