/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.38.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Enum } from "../common";

export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export type InvalidRSVPErrorInput = Enum<{ IncorrectAssetId: ContractIdInput, NotEnoughTokens: BigNumberish, InvalidEventID: IdentityInput }>;
export type InvalidRSVPErrorOutput = Enum<{ IncorrectAssetId: ContractIdOutput, NotEnoughTokens: BN, InvalidEventID: IdentityOutput }>;

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { value: string };
export type ContractIdOutput = ContractIdInput;
export type RSVPListInput = { unique_id: BigNumberish, max_capacity: BigNumberish, deposit: BigNumberish, owner: IdentityInput, name: string, num_of_rsvps: BigNumberish };
export type RSVPListOutput = { unique_id: BN, max_capacity: BN, deposit: BN, owner: IdentityOutput, name: string, num_of_rsvps: BN };

interface NinetieswhitelistAbiInterface extends Interface {
  functions: {
    create_list: FunctionFragment;
    rsvp: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'create_list', values: [BigNumberish, BigNumberish, string]): Uint8Array;
  encodeFunctionData(functionFragment: 'rsvp', values: [BigNumberish]): Uint8Array;

  decodeFunctionData(functionFragment: 'create_list', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'rsvp', data: BytesLike): DecodedValue;
}

export class NinetieswhitelistAbi extends Contract {
  interface: NinetieswhitelistAbiInterface;
  functions: {
    create_list: InvokeFunction<[capacity: BigNumberish, price: BigNumberish, list_name: string], RSVPListOutput>;
    rsvp: InvokeFunction<[list_id: BigNumberish], RSVPListOutput>;
  };
}
